### ISSUE TITLE
CKAN crashes after installing scheming and repeating

### ISSUE THREAD

**Issue by xbian** [open-data/ckanext-repeating#5]
Hi Ian,

We have a docker instance of CKAN and I am installing the repeating plugin because multiple authors are needed by our collaborator, I have installed both ckan-scheming and repeating with the multi authors config in the presets.ckan and config as follows:

```
ckan.plugins = stats text_view image_view recline_view officedocs_view googleanalytics dcat dcat_rdf_harvester dcat_json_harvester dcat_json_interface structured_data oaipmh repeating scheming_datasets



#   module-path:file to schemas being used
scheming_datasets*=ckanext.scheming.plugins:SchemingDatasetsPlugin
scheming.dataset_schemas = ckanext.spatialx:spatialx_schema.json
#                           ckanext.spatialx:spatialxy_schema.json
#   will try to load "spatialx_schema.json" and "spatialxy_schema.json"
#   as dataset schemas
#
#   URLs may also be used, e.g:
#
scheming.dataset_schemas = http://example.com/spatialx_schema.json
#
#   Preset files may be included as well. The default preset setting is:
scheming.presets = ckanext.scheming:presets.json
                   ckanext.repeating:presets.json

#   The is_fallback setting may be changed as well. Defaults to false:
scheming.dataset_fallback = false

```

But the CKAN just won't start after enabling the two extensions.

Could you help please?

Thanks
Xingdong

**Comment by wardi** [comment]
Hello Xingdong,

I need more information. What is the traceback you're seeing? What version of CKAN and Python are you using?

**Comment by xbian** [comment]
HI Ian,

Sorry for the late reply here are the logs when I enable the scheming_datasets as above, but if I take the last one out keep the repeating it will run fine.
```
ckan          | 2020-11-26 15:30:06,445 INFO  [ckan.lib.base]  /organization/088f6ec1-fa07-43a7-b767-c27a9b0706c1 render time 0.108 seconds
ckan          | 2020-11-26 15:30:09,614 INFO  [ckan.lib.base]  /organization/599ed918-ad91-472f-b9a0-32b3a945268b render time 0.140 seconds
ckan          | 2020-11-26 15:30:23,865 INFO  [ckan.lib.base]  /group/4ad56eff-4ff3-4699-a27c-fdeafcfc7ba4 render time 0.220 seconds
ckan          | 2020-11-26 15:30:27,089 INFO  [ckan.lib.base]  /dataset render time 0.094 seconds
ckan          | 2020-11-26 15:30:40,948 INFO  [ckan.lib.base]  /group/dfw-publications render time 0.162 seconds
ckan          | Traceback (most recent call last):
ckan          |   File "/usr/local/bin/ckan-paster", line 10, in <module>
ckan          |     sys.exit(run())
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
ckan          |     invoke(command, command_name, options, args[1:])
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
ckan          |     exit_code = runner.run(args)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
ckan          |     result = self.command()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 357, in command
ckan          |     self._load_config(cmd!='upgrade')
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 330, in _load_config
ckan          |     self.site_user = load_config(self.options.config, load_site_user)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 237, in load_config
ckan          |     load_environment(conf.global_conf, conf.local_conf)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/environment.py", line 112, in load_environment
ckan          |     p.load_all()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 140, in load_all
ckan          |     load(*plugins)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 168, in load
ckan          |     plugins_update()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 122, in plugins_update
ckan          |     environment.update_config()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/environment.py", line 164, in update_config
ckan          |     plugin.update_config(config)
ckan          |   File "/usr/lib/ckan/venv/src/ckanext-scheming/ckanext/scheming/plugins.py", line 167, in update_config
ckan          |     self._load_presets(config)
ckan          |   File "/usr/lib/ckan/venv/src/ckanext-scheming/ckanext/scheming/plugins.py", line 155, in _load_presets
ckan          |     for pp in _load_schema(f)['presets']:
ckan          |   File "/usr/lib/ckan/venv/src/ckanext-scheming/ckanext/scheming/plugins.py", line 384, in _load_schema
ckan          |     schema = _load_schema_module_path(url)
ckan          |   File "/usr/lib/ckan/venv/src/ckanext-scheming/ckanext/scheming/plugins.py", line 409, in _load_schema_module_path
ckan          |     return loader.load(open(p))
ckan          |   File "/usr/lib/ckan/venv/src/ckanext-scheming/ckanext/scheming/loader.py", line 11, in load
ckan          |     return json.load(f)
ckan          |   File "/usr/lib/python2.7/json/__init__.py", line 290, in load
ckan          |     **kw)
ckan          |   File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
ckan          |     return _default_decoder.decode(s)
ckan          |   File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
ckan          |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
ckan          |   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
ckan          |     obj, end = self.scan_once(s, idx)
ckan          | ValueError: Expecting property name: line 14 column 1 (char 428)
ckan exited with code 1
```
Thanks
Xingdong

**Comment by wardi** [comment]
this says there is a JSON error in your schema on line 14.

**Comment by xbian** [comment]
Thanks, So i have the repeating presets as follows:

```
{
	"scheming_presets_version": 1,
	"about": "scheming presets for repeating fields",
	"about_url": "http://github.com/open-data/ckanext-repeating",
	"presets": [{
			"preset_name": "repeating_text",
			"values": {
				"form_snippet": "repeating_text.html",
				"display_snippet": "repeating_text.html",
				"validators": "repeating_text",
				"output_validators": "repeating_text_output"
			}
		},
		{
			"field_name": "authors",
			"preset": "repeating_text",
			"label": "Author",
			"form_blanks": 3
		}
	]
}
```

Taken from the repeating plugin document example, and its now complaining about values:

```
ckan          | 2020-11-27 10:38:23,010 INFO  [ckan.lib.base]  /dataset/groups/5f10ca51-7c54-4720-8319-4253f8a65053 render time 0.254 seconds
ckan          | Traceback (most recent call last):
ckan          |   File "/usr/local/bin/ckan-paster", line 10, in <module>
ckan          |     sys.exit(run())
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
ckan          |     invoke(command, command_name, options, args[1:])
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
ckan          |     exit_code = runner.run(args)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
ckan          |     result = self.command()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 357, in command
ckan          |     self._load_config(cmd!='upgrade')
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 330, in _load_config
ckan          |     self.site_user = load_config(self.options.config, load_site_user)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 237, in load_config
ckan          |     load_environment(conf.global_conf, conf.local_conf)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/environment.py", line 112, in load_environment
ckan          |     p.load_all()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 140, in load_all
ckan          |     load(*plugins)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 168, in load
ckan          |     plugins_update()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 122, in plugins_update
ckan          |     environment.update_config()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/environment.py", line 164, in update_config
ckan          |     plugin.update_config(config)
ckan          |   File "/usr/lib/ckan/venv/src/ckanext-scheming/ckanext/scheming/plugins.py", line 167, in update_config
ckan          |     self._load_presets(config)
ckan          |   File "/usr/lib/ckan/venv/src/ckanext-scheming/ckanext/scheming/plugins.py", line 156, in _load_presets
ckan          |     _SchemingMixin._presets[pp['preset_name']] = pp['values']
ckan          | KeyError: 'values'
ckan exited with code 1
```

So our aim is to have multiple Authors in the ckan instance for the publications, what would be the best or correct config for this please?

Best regards
Xingdong

**Comment by wardi** [comment]
your presets JSON is not properly formatted. Presets need a "preset_name" and "values" key

**Comment by xbian** [comment]
So the second chunk can go into a values with a preset name?

**Comment by xbian** [comment]
Ok I have edited the json to:

```
{
	"scheming_presets_version": 1,
	"about": "scheming presets for repeating fields",
	"about_url": "http://github.com/open-data/ckanext-repeating",
	"presets": [{
			"preset_name": "repeating_text",
			"values": {
				"form_snippet": "repeating_text.html",
				"display_snippet": "repeating_text.html",
				"validators": "repeating_text",
				"output_validators": "repeating_text_output"
			}
		},
		{
			"preset_name": "repeating_author",
			"values": {
				"field_name": "authors",
				"preset": "repeating_text",
				"label": "Author",
				"form_blanks": 3
			}
		}
	]
}
```

in the config production.ini enabled both repeating and scheming_datasets plus the following preset settings

```
#   Preset files may be included as well. The default preset setting is:
scheming.presets = ckanext.scheming:presets.json
                   ckanext.repeating:presets.json

#   The is_fallback setting may be changed as well. Defaults to false:
scheming.dataset_fallback = false

```
I have disabled the following:

```
#   module-path:file to schemas being used
#scheming_datasets*=ckanext.scheming.plugins:SchemingDatasetsPlugin
#scheming.dataset_schemas = ckanext.spatialx:spatialx_schema.json
#                           ckanext.spatialx:spatialxy_schema.json
#   will try to load "spatialx_schema.json" and "spatialxy_schema.json"
#   as dataset schemas
#
#   URLs may also be used, e.g:
#
#scheming.dataset_schemas = http://example.com/spatialx_schema.json
```


But the CKAN still has one author entry in the adding new dataset page.

**Comment by xbian** [comment]
Solved with the forked repo:
https://github.com/eawag-rdm/ckanext-repeating_s
